name: Build and Deploy to S3

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm
    environment: ${{ github.event.release.prerelease && 'staging' || 'production' }}
    steps:
      - name: Output setup
        run: |
            echo "ENVIRONMENT: ${{ github.job.environment }}"
            echo "REPO: ${{ github.event.repository.name }}"
            echo "RELEASE: ${{ github.event.release.tag_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Manual approval (production only)
        if: ${{ !github.event.release.prerelease }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: jonathan-gaul
          minimum-approvals: 1
          issue-title: "Production deployment approval required"
          issue-body: "Please approve this production deployment."

      - name: Upload jar to S3
        id: upload
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          aws s3 cp "$JAR_FILE" s3://${{ vars.S3_BUCKET_NAME }}/
          echo "jar_file=$JAR_FILE" >> "$GITHUB_OUTPUT"        

      - name: Update lambda
        id: update-lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ vars.UPDATE_WORD_LAMBDA_NAME }} \
            --s3-bucket ${{ vars.S3_BUCKET_NAME }} \
            --s3-key $(basename "$JAR_FILE") \
            --publish
        env:
          AWS_REGION: eu-west-2
          JAR_FILE: ${{ steps.upload.outputs.jar_file }}